"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Share2,
  Trash2,
  Moon,
  Loader2,
  BookOpen,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import AudioPlayer from "@/components/AudioPlayer";
import StoryDisplay from "@/components/StoryDisplay";
import { useToast } from "@/hooks/use-toast";
import { getStoryById, updateStory, deleteStory } from "@/lib/storage";
import type { Story } from "@/types/story";

// Floating clouds animation
function FloatingClouds() {
  return (
    <div className="fixed inset-0 pointer-events-none overflow-hidden opacity-30">
      {[...Array(5)].map((_, i) => (
        <motion.div
          key={i}
          className="absolute bg-white/20 rounded-full blur-3xl"
          style={{
            width: `${150 + i * 50}px`,
            height: `${80 + i * 30}px`,
            left: `${i * 20}%`,
            top: `${10 + i * 15}%`,
          }}
          animate={{
            x: [0, 50, 0],
            opacity: [0.2, 0.4, 0.2],
          }}
          transition={{
            duration: 10 + i * 2,
            repeat: Infinity,
            ease: "easeInOut",
          }}
        />
      ))}
    </div>
  );
}

export default function StoryPage() {
  const params = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const { toast } = useToast();

  const [story, setStory] = useState<Story | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGeneratingAudio, setIsGeneratingAudio] = useState(false);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [shouldAutoPlay, setShouldAutoPlay] = useState(false);
  const hasAutoGeneratedRef = useRef(false);

  // Check if this is a new story (auto-generate audio)
  const isNewStory = searchParams.get("new") === "true";

  // Load story from localStorage
  useEffect(() => {
    const storyId = params.id as string;
    if (!storyId) {
      router.push("/");
      return;
    }

    const loadedStory = getStoryById(storyId);
    if (!loadedStory) {
      toast({
        title: "Story not found",
        description: "This story doesn't exist or has been deleted.",
        variant: "destructive",
      });
      router.push("/");
      return;
    }

    setStory(loadedStory);
    if (loadedStory.audioUrl) {
      setAudioUrl(loadedStory.audioUrl);
    }
    setIsLoading(false);
  }, [params.id, router, toast]);

  // Generate audio for the story
  const handleGenerateAudio = useCallback(async (autoPlay: boolean = false) => {
    if (!story) return;

    setIsGeneratingAudio(true);

    try {
      const response = await fetch("/api/text-to-speech", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text: story.content,
          storyId: story.id,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to generate audio");
      }

      // Get audio blob
      const audioBlob = await response.blob();
      const audioBlobUrl = URL.createObjectURL(audioBlob);

      // Get duration from header
      const audioDuration = parseInt(
        response.headers.get("X-Audio-Duration") || "0",
        10
      );

      // Update state - set autoplay flag before setting URL
      if (autoPlay) {
        setShouldAutoPlay(true);
      }
      setAudioUrl(audioBlobUrl);

      // Update story in storage
      updateStory(story.id, {
        audioUrl: audioBlobUrl,
        audioDuration,
      });

      toast({
        title: "Audio Ready!",
        description: autoPlay
          ? "Playing your bedtime story now..."
          : "Your bedtime story narration is ready to play.",
      });
    } catch (error) {
      console.error("Audio generation error:", error);
      toast({
        title: "Audio Generation Failed",
        description:
          error instanceof Error
            ? error.message
            : "Could not generate audio. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingAudio(false);
    }
  }, [story, toast]);

  // Auto-generate audio for new stories
  useEffect(() => {
    if (isNewStory && story && !audioUrl && !isGeneratingAudio && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      // Small delay to let the page render first
      const timer = setTimeout(() => {
        handleGenerateAudio(true); // Pass true for autoPlay
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [isNewStory, story, audioUrl, isGeneratingAudio, handleGenerateAudio]);

  // Delete story
  const handleDelete = () => {
    if (!story) return;

    const confirmed = window.confirm(
      "Are you sure you want to delete this story? This cannot be undone."
    );

    if (confirmed) {
      deleteStory(story.id);
      toast({
        title: "Story Deleted",
        description: "The story has been removed from your library.",
      });
      router.push("/library");
    }
  };

  // Share story
  const handleShare = async () => {
    if (!story) return;

    const shareData = {
      title: story.title,
      text: `Check out this bedtime story I created for ${story.childName}: "${story.title}"`,
      url: window.location.href,
    };

    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        await navigator.clipboard.writeText(
          `${shareData.text}\n${shareData.url}`
        );
        toast({
          title: "Link Copied!",
          description: "Story link copied to clipboard.",
        });
      }
    } catch (error) {
      // User cancelled share or error
      console.log("Share cancelled or failed:", error);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-dream-purple-900 via-dream-purple-800 to-dream-blue-900 flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center"
        >
          <Loader2 className="h-12 w-12 text-dream-purple-200 animate-spin mx-auto mb-4" />
          <p className="text-dream-purple-200">Loading story...</p>
        </motion.div>
      </div>
    );
  }

  if (!story) {
    return null;
  }

  return (
    <main className="min-h-screen bg-gradient-to-b from-dream-purple-100 via-dream-purple-50 to-dream-blue-50 relative">
      <FloatingClouds />

      {/* Header */}
      <header className="relative z-10 bg-white/80 backdrop-blur-sm border-b border-dream-purple-100 sticky top-0">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <Button
            variant="ghost"
            onClick={() => router.back()}
            className="text-dream-purple-700 hover:text-dream-purple-800"
          >
            <ArrowLeft className="mr-2 h-5 w-5" />
            Back
          </Button>

          <div className="flex items-center gap-2">
            <div className="bg-gradient-to-br from-dream-purple-100 to-dream-pink-100 p-2 rounded-xl">
              <Moon className="h-5 w-5 text-dream-purple-600" />
            </div>
            <span className="text-sm font-medium text-dream-purple-700 hidden sm:inline">
              DreamTales AI
            </span>
          </div>

          <div className="flex gap-2">
            <Button
              variant="ghost"
              size="icon"
              onClick={handleShare}
              className="text-dream-purple-600 hover:text-dream-purple-700"
            >
              <Share2 className="h-5 w-5" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              onClick={handleDelete}
              className="text-red-500 hover:text-red-600 hover:bg-red-50"
            >
              <Trash2 className="h-5 w-5" />
            </Button>
          </div>
        </div>
      </header>

      {/* Content */}
      <div className="relative z-10 max-w-4xl mx-auto px-4 py-8">
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Story Content */}
          <div className="lg:col-span-2">
            <StoryDisplay story={story} />
          </div>

          {/* Audio Player Sidebar */}
          <div className="lg:col-span-1">
            <div className="sticky top-24">
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 }}
              >
                <h3 className="text-lg font-semibold text-dream-purple-800 mb-4 flex items-center gap-2">
                  <BookOpen className="h-5 w-5" />
                  Listen to Story
                </h3>
                <AudioPlayer
                  audioUrl={audioUrl}
                  isGenerating={isGeneratingAudio}
                  onGenerateAudio={() => handleGenerateAudio(true)}
                  storyTitle={story.title}
                  autoPlay={shouldAutoPlay}
                />
              </motion.div>

              {/* Quick Actions */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
                className="mt-6"
              >
                <Button
                  variant="outline"
                  className="w-full"
                  onClick={() => router.push("/")}
                >
                  Create Another Story
                </Button>
              </motion.div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
